app:
  name: TenHeigh CMS
  version: 1.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tenheigh?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"